# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Typings' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Typings

  target 'Typings-tvOSTests' do
    inherit! :search_paths
    # Pods for testing

  end

  target 'TypingsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Typings-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Typings-tvOS

  target 'Typings-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
